language: python
python:
  - "3.7"
  - "3.8"
# command to install dependencies
install:
  - pip install requests pyyaml pytest pytest-cov
  - pip install numpy
  - pip install matplotlib
# command to run tests
script:
  - pytest
  - pytest --cov
  - pytest --doctest-modules


